package lottery.domains.content.global;

public enum DbServerSyncEnum {
	LOTTERY,
	LOTTERY_OPEN_TIME,
	LOTTERY_PLAY_RULES,
	LOTTERY_TYPE,
	SYS_CODE_AMOUNT,
	SYS_CODE_QUOTA,
	SYS_CONFIG,
	SYS_NOTICE,
	ACTIVITY,
	CDN,
	SYS_PLATFORM,
	HIT_RANKING,
	PAYMENT_CHANNEL,
	PAYMENT_CHANNEL_BANK
}