spring:
  profiles:
    active: dev
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  devtools:
    restart:
      enabled: true  
  mail: 
    host: smtp.qq.com
    username: 1558281773@qq.com
    password: vozwkfddfarchehe
    default-encoding: UTF-8
    port: 587
    properties:
      mail: 
        smtp:
          auth: true
          starttls: 
            enable: true
            required: true      
  output:
    ansi:
      enabled: always 
            
server:
  port: 10001
  session-timeout: 1800
  
mybatis: 
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mapping/**/*Mapper.xml
  typeAliasesPackage: com.xxq.messageborad.entity 
  
debug: false

#如果logback中设置了日志级别 此处可不设置
#logging:
#  level:
#    root: info
 
    