spring:
  profiles:
    active: dev
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  devtools:
    restart:
      enabled: true  
          
server:
  port: 10001
  session-timeout: 1800
  
mybatis: 
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mapping/**/*Mapper.xml
  typeAliasesPackage: com.xxq.messageborad.entity

  