package lottery.domains.content.global;

public enum DbServerSyncEnum {
	LOTTERY,
	LOTTERY_OPEN_TIME,
	LOTTERY_PLAY_RULES,
	LOTTERY_TYPE,
	PAYMENT_CARD,
	PAYMENT_CHANNEL,
	PAYMENT_CHANNEL_BANK,
	SYS_CODE_AMOUNT,
	SYS_CODE_QUOTA,
	SYS_CONFIG,
	SYS_NOTICE,
	ACTIVITY,
	ADMIN_CDN,
	SYS_PLATFORM,
	HIT_RANKING
}